### ISSUE TITLE
运行models.py 无法插入表

### ISSUE THREAD

**Issue by xh21baobao** [xzkzdx/weixin-spider#3]
C:\conda\python.exe D:/code/weixin-spider-master/webapp/models.py
Traceback (most recent call last):
  File "C:\conda\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\conda\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "C:\conda\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "C:\conda\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "C:\conda\lib\site-packages\MySQLdb\connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/code/weixin-spider-master/webapp/models.py", line 123, in <module>
    db.create_all()
  File "C:\conda\lib\site-packages\flask_sqlalchemy\__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "C:\conda\lib\site-packages\flask_sqlalchemy\__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "C:\conda\lib\site-packages\sqlalchemy\sql\schema.py", line 4294, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "C:\conda\lib\site-packages\sqlalchemy\engine\base.py", line 2036, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "C:\conda\lib\site-packages\sqlalchemy\engine\base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\conda\lib\site-packages\sqlalchemy\sql\visitors.py", line 132, in traverse_single
    return meth(obj, **kw)
  File "C:\conda\lib\site-packages\sqlalchemy\sql\ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "C:\conda\lib\site-packages\sqlalchemy\sql\visitors.py", line 132, in traverse_single
    return meth(obj, **kw)
  File "C:\conda\lib\site-packages\sqlalchemy\sql\ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "C:\conda\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "C:\conda\lib\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "C:\conda\lib\site-packages\sqlalchemy\engine\base.py", line 1050, in _execute_ddl
    compiled,
  File "C:\conda\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\conda\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\conda\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\conda\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\conda\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\conda\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "C:\conda\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "C:\conda\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "C:\conda\lib\site-packages\MySQLdb\connections.py", line 226, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes')
[SQL: 
CREATE TABLE wx_account (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	account_name VARCHAR(50), 
	account_id VARCHAR(30), 
	account_biz VARCHAR(20), 
	account_id_unique VARCHAR(30), 
	account_logo VARCHAR(300), 
	account_desc VARCHAR(300), 
	account_url VARCHAR(500), 
	created VARCHAR(20), 
	status INTEGER, 
	offset INTEGER, 
	counts INTEGER, 
	end BOOL, 
	fail BOOL, 
	`update` VARCHAR(20), 
	PRIMARY KEY (id), 
	UNIQUE (account_id), 
	UNIQUE (account_biz), 
	UNIQUE (account_id_unique), 
	UNIQUE (account_logo), 
	UNIQUE (account_url), 
	CHECK (end IN (0, 1)), 
	CHECK (fail IN (0, 1)), 
	UNIQUE (account_id), 
	UNIQUE (account_biz), 
	UNIQUE (account_id_unique), 
	UNIQUE (account_logo), 
	UNIQUE (account_url), 
	CHECK (end IN (0, 1)), 
	CHECK (fail IN (0, 1))
)CHARSET=utf8mb4

]
(Background on this error at: http://sqlalche.me/e/e3q8)

Process finished with exit code 1

**Comment by xzkzdx** [comment]
部分无法插入原因在于该字段内容过长，可以考虑变更数据库字段长度，类似这种可先行自定义数据模型中的字符长度

**Comment by xh21baobao** [comment]
这个已经超过能力范围了 提升了长度 。。。之后呢 由769变成1000了 我看了一下代码 这个800的 都有 变成多少好像影响已经不是那么大了。

**Comment by xzkzdx** [comment]
公众号id留一下





------------------ 原始邮件 ------------------
发件人: xh21baobao <notifications@github.com&gt;
发送时间: 2019年9月6日 17:17
收件人: xzkzdx/weixin-spider <weixin-spider@noreply.github.com&gt;
抄送: 詹生松 <1968199077@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xzkzdx/weixin-spider] 运行models.py 无法插入表 (#3)




这个已经超过能力范围了 提升了长度 。。。之后呢 由769变成1000了 我看了一下代码 这个800的 都有 变成多少好像影响已经不是那么大了。
