### ISSUE TITLE
运行models.py时候报错了 找不到webapp模块

### ISSUE THREAD

**Issue by WHU2018302110329** [xzkzdx/weixin-spider#5]
在pycharm环境下运行models.py报错 找不到一些包 希望可以帮忙分析一下

Traceback (most recent call last):
  File "D:/spider/weixin_spider/weixin-spider-master/webapp/models.py", line 7, in <module>
    from webapp import db
  File "D:\spider\weixin_spider\weixin-spider-master\webapp\__init__.py", line 14, in <module>
    from webapp.wxapp import wx_app as wx_app_blueprint
  File "D:\spider\weixin_spider\weixin-spider-master\webapp\wxapp\__init__.py", line 10, in <module>
    from webapp.wxapp import selffilter
  File "D:\spider\weixin_spider\weixin-spider-master\webapp\wxapp\selffilter.py", line 7, in <module>
    from pyquery import PyQuery
  File "D:\anaconda\lib\site-packages\pyquery\__init__.py", line 7, in <module>
    from .pyquery import PyQuery  # NOQA
  File "D:\anaconda\lib\site-packages\pyquery\pyquery.py", line 10, in <module>
    from lxml import etree
ImportError: DLL load failed: 找不到指定的模块。

Process finished with exit code 1

**Comment by manyhelp** [comment]
同问

**Comment by yysnyang** [comment]
+1

**Comment by yysnyang** [comment]
PS E:\weixin_context\weixin-spider\webapp> python models.py
Traceback (most recent call last):
  File "models.py", line 7, in <module>
    from webapp import db
ModuleNotFoundError: No module named 'webapp'

**Comment by Whusan** [comment]
webapp模块下的db文件缺失了啊 大佬可以私发一下不  QQ:2143549151 邮箱：2143549151@qq.com

**Comment by Wdiviner** [comment]
把webapp模块下的model.py文件复制一份到上级目录，然后在上级目录执行就能把导入表结构到数据库里了
